=== hans/jido-data/verbs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
	TODO define vocabulary identification
	PUBLIC ID: -//vendor//vocabulary//EN
	SYSTEM ID: http://server/path/verbs.dtd

-->

<!--
	An example how to use this DTD from your XML document:
	
	<?xml version="1.0"?>

	<!DOCTYPE verbs SYSTEM "verbs.dtd">

	<verbs>
	...
	</verbs>
-->

<!ELEMENT verbs (verb|verbset)*>
<!ATTLIST verbs
	lang CDATA #REQUIRED
  >

<!ELEMENT verbset (participles, mood+)>
<!ATTLIST verbset
	id CDATA #REQUIRED
	inherit CDATA #IMPLIED
  >

<!ELEMENT participles (participle+)>

<!ELEMENT participle (mod?, prepend?, append?)>
<!ATTLIST participle
	irregular CDATA #IMPLIED
	endlength CDATA #REQUIRED
	id CDATA #REQUIRED
  >

<!ELEMENT append (#PCDATA)>

<!ELEMENT mood (group+)>
<!ATTLIST mood
	id CDATA #REQUIRED
  >

<!ELEMENT group (pdgmgroup+)>
<!ATTLIST group
	endlength CDATA #REQUIRED
	id CDATA #REQUIRED
  >

<!ELEMENT pdgmgroup (paradigm*)>
<!ATTLIST pdgmgroup
	id CDATA #REQUIRED
  >

<!ELEMENT paradigm (mod|prepend|append)*>
<!ATTLIST paradigm
	irregular CDATA #IMPLIED
	id CDATA #REQUIRED
  >

<!ELEMENT prepend (#PCDATA)>

<!ELEMENT mod EMPTY>
<!ATTLIST mod
	replace CDATA #REQUIRED
	search CDATA #REQUIRED
	match CDATA #REQUIRED
  >

<!ELEMENT verb (participles*, mood*)>
<!ATTLIST verb
	ref CDATA #IMPLIED
	inherit CDATA #IMPLIED
	word CDATA #IMPLIED
  >

=== hans/jido-data/fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE verbs SYSTEM "verbs.dtd">-->
<verbs lang="fr">
	<meta>
		<forms>
			<form desc="indicative present">prs</form>
			<form desc="indicative passé composé">pcomp</form>
			<form desc="indicative imperfect">imp</form>
			<form desc="indicative pluperfect">plu</form>
			<form desc="indicative future simple">futsimp</form>
			<form desc="indicative future perfect">futant</form>
			<form desc="indicative past simple">passimp</form>
			<form desc="indicative past anterior">pstant</form>
			<form desc="subjunctive present">subprs</form>
			<form desc="subjunctive past">subpst</form>
			<form desc="subjunctive imperfect">subimp</form>
			<form desc="subjunctive pluperfect">subplu</form>
			<form desc="conditional present">cprs</form>
			<form desc="conditional past">cpst</form>
			<form desc="conditional past II">cpst2</form>
			<form desc="imperative present">impprs</form>
			<form desc="imperative past">imppst</form>
		</forms>
		
		<fallbacks>
			<fallback desc="-er verb" regex="er$" ref="reg.er" />
			<fallback desc="-ir verb" regex="ir$" ref="reg.ir" />
			<fallback desc="-re verb" regex="re$" ref="reg.re" />
		</fallbacks>
		
		<paradigms>
			<paradigm desc="1st-person singular" person="1" quant="sg" />
			<paradigm desc="1st-person plural" person="1" quant="pl" />
			<paradigm desc="2nd-person singular" person="2" quant="sg" />
			<paradigm desc="2nd-person plural" person="2" quant="pl" />
			<paradigm desc="3rd-person singular" person="3" quant="sg" />
			<paradigm desc="3rd-person plural" person="3" quant="pl" />
		</paradigms>
	</meta>
	
	<verbset id="reg.er">
		<participles>
			<participle id="present">
				<append>ant</append>
				<endlength>2</endlength>
			</participle>
			<participle id="past" endlength="2">
				<append>é</append>
			</participle>
		</participles>
		<group id="prs">
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>e</append>
				</paradigm>
				<paradigm id="pl">
					<append>ons</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>es</append>
				</paradigm>
				<paradigm id="pl">
					<append>ez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>e</append>
				</paradigm>
				<paradigm id="pl">
					<append>ent</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="pcomp">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>ai </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>avons </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>as </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>avez </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>a </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>ont </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="imp">
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>ais</append>
				</paradigm>
				<paradigm id="pl">
					<append>ions</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>ais</append>
				</paradigm>
				<paradigm id="pl">
					<append>iez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>ait</append>
				</paradigm>
				<paradigm id="pl">
					<append>aient</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="plu">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>avais </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>avions </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>avais </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>aviez </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>avait </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>avaient </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="futsimp">
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>ai</append>
				</paradigm>
				<paradigm id="pl">
					<append>ons</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>as</append>
				</paradigm>
				<paradigm id="pl">
					<append>ez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>a</append>
				</paradigm>
				<paradigm id="pl">
					<append>ont</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="futant">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>aurai </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>aurons </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>auras </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>aurez </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>aura </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>auront </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="passimp">
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>ai</append>
				</paradigm>
				<paradigm id="pl">
					<append>âmes</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>as</append>
				</paradigm>
				<paradigm id="pl">
					<append>âtes</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>a</append>
				</paradigm>
				<paradigm id="pl">
					<append>èrent</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="pstant">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>eus </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eûmes </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>eus </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eûtes </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>eut </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eurent </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="subprs">
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>e</append>
				</paradigm>
				<paradigm id="pl">
					<append>ions</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>es</append>
				</paradigm>
				<paradigm id="pl">
					<append>iez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>e</append>
				</paradigm>
				<paradigm id="pl">
					<append>ent</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="subimp">
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>asse</append>
				</paradigm>
				<paradigm id="pl">
					<append>assions</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>asses</append>
				</paradigm>
				<paradigm id="pl">
					<append>assiez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>ât</append>
				</paradigm>
				<paradigm id="pl">
					<append>assent</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="subpst">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>aie </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>ayons </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>aies </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>ayez </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>ait </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>aient </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="subplu">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
				<paradigm id="sg">
					<prepend>eusse </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eussions </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<prepend>eusses </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eussiez </prepend>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<prepend>eût </prepend>
				</paradigm>
				<paradigm id="pl">
					<prepend>eussent </prepend>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="cprs">
			<pdgmgroup id="1">
				<paradigm id="sg">
					<append>ais</append>
				</paradigm>
				<paradigm id="pl">
					<append>ions</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="2">
				<paradigm id="sg">
					<append>ais</append>
				</paradigm>
				<paradigm id="pl">
					<append>iez</append>
				</paradigm>
			</pdgmgroup>
			<pdgmgroup id="3">
				<paradigm id="sg">
					<append>ait</append>
				</paradigm>
				<paradigm id="pl">
					<append>aient</append>
				</paradigm>
			</pdgmgroup>
		</group>
		<group id="cpst">
			<append>é</append>
			<endlength>2</endlength>
			
			<pdgmgroup id="1">
